version: '3'

services:
  spring-app:
    image: egon89/spring-guide
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      # it mounts the project directory (current directory) on the host to /data/app
      # inside the container, allowing you to modify the code on the fly, without having to rebuild the image
      - /data/app
    ports:
      - '${APP_HOST_PORT:-8081}:${PORT:-8081}'
      - '5005:5005'
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  postgres:
    hostname: ${DB_HOST}
    image: postgres:13-alpine
    restart: unless-stopped
    ports:
      - "${DB_HOST_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/database/entrypoint:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - APP_DB_USER=${APP_DB_USER}
      - APP_DB_PASSWORD=${APP_DB_PASSWORD}
      - APP_DB_NAME=${APP_DB_NAME}

volumes:
  postgres-data:
