apiVersion: v1
kind: Service
metadata:
  namespace: dev
  creationTimestamp: null
  labels:
    app: sg-core
  name: sg-core
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sg-core
  type: ClusterIP
status:
  loadBalancer: {}
